### ISSUE TITLE
SQLSpecialColumns ODBC API does not return Columns part of UNIQUE INDEX on YugaByteDB

### ISSUE THREAD

**Issue by raddakal** [postgresql-interfaces/psqlodbc#79]
Hello,

Its a very common use case where an explicit primary key is not defined on the table but instead rely on the unique index. The ODBC driver is expected to return the columns that are of the UNIQUE index when SQLSpecialColumns ODBCAPI is called.

[SQLSpecialColumns.zip](https://github.com/user-attachments/files/17919927/SQLSpecialColumns.zip)

Environment details:
--------------------

OS: 
OEL8 Linux 64bit (el8uek.x86_64)

Database: 
Yugabyte DB 
PostgreSQL
Version 11.02.0001 PostgreSQL 11.2-YB-2024.1.1.0-b0
ODBC Version 03.52.0000

Driver:
Driver Information:
psqlodbcw.so
Version 17.00.0002
ODBC Version 03.51.

I have attached SQLSpecialColumns.zip which contains the standalone ODBC program along with the detailed steps to reproduce the issue.

Our major release is blocked because of this issue. 
A quick resolution/workaround would be highly appreciated.

Thanks.

**Comment by davecramer** [comment]
What product are you releasing ?

**Comment by raddakal** [comment]
The reported issue is not just confined to YugaByteDB but it is seen with PostgreSQL database as well.

I am part of Oracle and We certify native ODBC driver for PostgreSQL with one of the Data integration products.  This issue is critical for us.


Thanks.

**Comment by davecramer** [comment]
@raddakal OK, any chance you can provide a PR? Otherwise I will attempt to get this shortly

**Comment by davecramer** [comment]
Ok, I was able to reproduce the problem. Give me some time to see about a fix

**Comment by davecramer** [comment]
I'm working on this. What would you expect for a multi-column primary key or unique index ?

**Comment by davecramer** [comment]
@raddakal can you test https://github.com/postgresql-interfaces/psqlodbc/pull/85 ?

**Comment by davecramer** [comment]
Thanks, I'll take a look

**Comment by davecramer** [comment]
@abhi-555 
In the Pull Request #85 I created a table testtab1 
```
CREATE TABLE test_special( id integer primary key, ival integer);
CREATE UNIQUE index test_special_ui on public.test_special(ival);
```
Then in the test you can see the output as:

```
Result set:
NULL	public	test_special	id	int4	int4	4	4	0	1
NULL	public	test_special	ival	int4	int4	4	4	0	1
```

Are you able to run the test on your end and see the same ?

**Comment by davecramer** [comment]
Fixed by #85

**Comment by abhi-555** [comment]
I am still not receiving zero rows upon running SQLSpecialColumns in the given test case in the shared standalone.
Can you please run the test case in the standalone [SQLSpecialColumns.zip](https://github.com/user-attachments/files/17919927/SQLSpecialColumns.zip) and confirm if this is working for you?
